name: Add IAM issues to Internal projects

on:
  issues:
    types: [opened, labeled]

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - name: Add issue to IAM Patches
        if: github.event.action == 'opened' || contains(github.event.issue.labels.*.name, 'Patch') || contains(github.event.issue.labels.*.name, 'Type/Patch')
        uses: actions/add-to-project@main
        with:
          project-url: https://github.com/orgs/is-playground/projects/1
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
          labeled: Patch, Type/Patch
          label-operator: OR

      - name: Add issue to IAM Internal Patches
        if: github.event.action == 'opened' || contains(github.event.issue.labels.*.name, 'Type/Internal-Patch') || contains(github.event.issue.labels.*.name, 'Type/proactive-patch')
        uses: actions/add-to-project@main
        with:
          project-url: https://github.com/orgs/is-playground/projects/1
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
          labeled: Type/Internal-Patch, Type/proactive-patch
          label-operator: OR

      - name: Add issue to IAM Internals
        if: github.event.action == 'opened' || !contains(github.event.issue.labels.*.name, 'Patch') && !contains(github.event.issue.labels.*.name, 'Type/Other') && !contains(github.event.issue.labels.*.name, 'Type/PeerReview') && !contains(github.event.issue.labels.*.name, 'security-report-analysis') && !contains(github.event.issue.labels.*.name, 'Type/Internal-Patch') && !contains(github.event.issue.labels.*.name, 'Type/proactive-patch')
        uses: actions/add-to-project@main
        with:
          project-url: https://github.com/orgs/is-playground/projects/2
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
          labeled: Type/Patch, Type/Other, Type/PeerReview, security-report-analysis, Type/Internal-Patch, Type/proactive-patch
          label-operator: NOT

      - name: Add issue to IAM Other Tasks
        if: github.event.action == 'opened' || contains(github.event.issue.labels.*.name, 'Type/Other') || contains(github.event.issue.labels.*.name, 'Type/PeerReview') || contains(github.event.issue.labels.*.name, 'security-report-analysis')
        uses: actions/add-to-project@main
        with:
          project-url: https://github.com/orgs/is-playground/projects/3
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
          labeled: Type/Other, Type/PeerReview, security-report-analysis
          label-operator: OR
