name: Add IAM issues to Internal projects

on:
  issues:
    types: [opened, labeled]

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - name: Add issue to IAM Patches
        if: (github.event.action == 'opened' && contains(fromJson('["Patch", "Type/Patch"]'), github.event.issue.labels.*.name)) || (github.event.action == 'labeled' && (github.event.label.name == 'Patch' || github.event.label.name == 'Type/Patch'))
        uses: actions/add-to-project@main
        with:
          project-url: https://github.com/orgs/is-playground/projects/1
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
          labeled: Patch, Type/Patch
          label-operator: OR

      - name: Add issue to IAM Internal Patches
        if: (github.event.action == 'opened' && contains(fromJson('["Type/Internal-Patch", "Type/proactive-patch"]'), github.event.issue.labels.*.name)) || (github.event.action == 'labeled' && (github.event.label.name == 'Type/Internal-Patch' || github.event.label.name == 'Type/proactive-patch'))
        uses: actions/add-to-project@main
        with:
          project-url: https://github.com/orgs/is-playground/projects/1
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
          labeled: Type/Internal-Patch, Type/proactive-patch
          label-operator: OR

      - name: Add issue to IAM Internals
        if: (github.event.action == 'opened' && !contains(fromJson('["Patch", "Type/Other", "Type/PeerReview", "security-report-analysis", "Type/Internal-Patch", "Type/proactive-patch"]'), github.event.issue.labels.*.name)) || (github.event.action == 'labeled' && !contains(fromJson('["Patch", "Type/Other", "Type/PeerReview", "security-report-analysis", "Type/Internal-Patch", "Type/proactive-patch"]'), [github.event.label.name]))
        uses: actions/add-to-project@main
        with:
          project-url: https://github.com/orgs/is-playground/projects/2
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
          labeled: Type/Patch, Type/Other, Type/PeerReview, security-report-analysis, Type/Internal-Patch, Type/proactive-patch
          label-operator: NOT

      - name: Add issue to IAM Other Tasks
        if: (github.event.action == 'opened' && contains(fromJson('["Type/Other", "Type/PeerReview", "security-report-analysis"]'), github.event.issue.labels.*.name)) || (github.event.action == 'labeled' && (github.event.label.name == 'Type/Other' || github.event.label.name == 'Type/PeerReview' || github.event.label.name == 'security-report-analysis'))
        uses: actions/add-to-project@main
        with:
          project-url: https://github.com/orgs/is-playground/projects/3
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
          labeled: Type/Other, Type/PeerReview, security-report-analysis
          label-operator: OR
